# Generated by Django 4.0.3 on 2022-04-08 07:03

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Chat',
            fields=[
                ('chat_id', models.IntegerField(primary_key=True, serialize=False)),
                ('title', models.TextField(blank=True, null=True)),
                ('feed', models.TextField()),
                ('time', models.TimeField(auto_now_add=True)),
                ('date', models.DateField(auto_now_add=True)),
                ('feed_type', models.CharField(choices=[('p', 'positive'), ('n', 'negative')], default=None, max_length=1)),
                ('tags', models.JSONField(default={})),
                ('author_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='chat', to=settings.AUTH_USER_MODEL)),
                ('downvotes', models.ManyToManyField(related_name='chat2', to=settings.AUTH_USER_MODEL)),
                ('upvotes', models.ManyToManyField(related_name='chat1', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
